nickname = "Stu"
stamina = 9.456461654644
print("FORMATANDO CARACTERES E ESPAÇOS")
print("Ola, como vai voce hoje mano {:20}?".format(nickname))
print("Ola, como vai voce hoje mano {:>20}?".format(nickname))
print("Ola, como vai voce hoje mano {:^20}?".format(nickname))
print("Ola, como vai voce hoje mano {:#^20}?".format(nickname))
print(" ")
print("----------------------------------------------")
print("FORMATANDO CASAS APÓS VIRGULA NO PONTO FLUTUANTE")
print("O nivel de stamina do {} é de {:.3f}".format(nickname, stamina))
print(" ")
print("----------------------------------------------")
print("JUNTANDO PRINTS DIFERENTES NA MESMA LINHA")
print("{} fez login no servidor".format(nickname), end=" ")
print("e seu nivel de stamina é de {:.3f}".format(stamina))
print(" ")
print("-----------------------------------------------")
print("QUEBRANDO UMA LINHA EM MAIS LINHAS")
print("{} fez login no servidor e \nseu nivel de stamina é de {:.3f}".format(nickname, stamina))